spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:sgrunt
    username: "sgrunt"
    password: "sgrunt"

logging:
  pattern:
    console: "%d [%thread] %-5level %logger{36} - %msg%n"

sgruntbot:
  config:
    chat-id: -676046724
    proxy: "http://localhost:8888"
    baseRestUrl: http://localhost:8081
